apiVersion: v1
kind: Journey
metadata:
  name: auth-outbound-client-credentials
  version: 0.1.0
  description: >
    Call a third-party API using OAuth2 client credentials for outbound auth.
spec:
  policies:
    httpClientAuth:
      default: backendDefault
      definitions:
        backendDefault:
          kind: oauth2ClientCredentials
          tokenEndpoint: https://auth.example.com/oauth2/token
          auth:
            method: clientSecretPost
            clientId: orders-service
            clientSecretRef: secret://oauth/clients/orders-service
          form:
            grant_type: client_credentials
            scope: orders.read

  apis:
    backend:
      openApiRef: apis/backend.openapi.yaml

  start: callBackend

  states:
    callBackend:
      type: task
      task:
        kind: httpCall
        operationRef: backend.getOrder
        auth:
          policyRef: backendDefault
        params:
          path:
            orderId: "${context.orderId}"
          headers:
            Accept: application/json
        timeoutMs: 5000
        resultVar: api
      next: decide

    decide:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.api.ok == true and context.api.status == 200
          next: done
      default: failed

    done:
      type: succeed
      outputVar: api

    failed:
      type: fail
      errorCode: OUTBOUND_CALL_FAILED
      reason: "Backend call failed or did not return 200"
