apiVersion: v1
kind: Journey
metadata:
  name: cache-user-profile
  version: 0.1.0
  description: Cache user profiles in an in-memory cache for faster reads.
spec:
  apis:
    users: { openApiRef: apis/users.openapi.yaml }
  resources:
    caches:
      defaultCache:
        kind: inMemory
        maxEntries: 10000
        ttlSeconds: 300
  input:
    schema:
      title: cache-user-profile input context
      type: object
      required: [userId]
      properties:
        userId:
          type: string
        country:
          type: string
      additionalProperties: true
  output:
    schema:
      title: cache-user-profile output (user profile)
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
          format: email
        country:
          type: string
      additionalProperties: true
  start: normalise
  states:
    normalise:
      type: transform
      transform:
        mapper:
          lang: dataweave
          expr: |
            {
              user: {
                id: context.userId,
                country: context.country default: null
              }
            }
        target:
          kind: context
          path: user
      next: readCache

    readCache:
      type: task
      task:
        kind: cacheGet
        cacheRef: defaultCache
        key:
          mapper:
            lang: dataweave
            expr: |
              context.user.id
        resultVar: cachedUser
      next: chooseSource

    chooseSource:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.cachedUser != null
          next: useCache
      default: fetchRemote

    useCache:
      type: transform
      transform:
        mapper:
          lang: dataweave
          expr: |
            context.cachedUser
        target:
          kind: var
        resultVar: profile
      next: done

    fetchRemote:
      type: task
      task:
        kind: httpCall
        operationRef: users.getUserById
        params:
          path: { userId: "${context.user.id}" }
          headers: { Accept: application/json }
        timeoutMs: 5000
        resultVar: remote
      next: storeCache

    storeCache:
      type: task
      task:
        kind: cachePut
        cacheRef: defaultCache
        key:
          mapper:
            lang: dataweave
            expr: |
              context.user.id
        value:
          mapper:
            lang: dataweave
            expr: |
              context.remote.body
        ttlSeconds: 600
      next: fromRemote

    fromRemote:
      type: transform
      transform:
        mapper:
          lang: dataweave
          expr: |
            context.remote.body
        target:
          kind: var
        resultVar: profile
      next: done

    done:
      type: succeed
      outputVar: profile
