apiVersion: v1
kind: Journey
metadata:
  name: http-failure-branch
  version: 0.1.0
spec:
  input:
    schema:
      type: object
      required: [inputId]
      additionalProperties: true
      properties:
        inputId:
          type: string
  output:
    schema:
      type: object
      properties:
        status:
          type: integer
        ok:
          type: boolean
        headers:
          type: object
          additionalProperties:
            type: string
        body: {}
        error:
          type: object
          properties:
            type:
              type: string
            message:
              type: string
          additionalProperties: true
      additionalProperties: true
  # Error handling:
  # - Branches on `api.ok` and either succeeds with the raw HTTP result or fails with a stable error code.
  # - The exposed `{status, ok, headers, body, error{type,message,...}}` shape is a simple custom error envelope;
  #   internally, the engine still treats Problem Details as the canonical error model (ADR-0003).
  apis:
    items: { openApiRef: apis/items.openapi.yaml }
    users: { openApiRef: apis/users.openapi.yaml }
    accounts: { openApiRef: apis/accounts.openapi.yaml }
    serviceA: { openApiRef: apis/serviceA.openapi.yaml }
    serviceB: { openApiRef: apis/serviceB.openapi.yaml }
  start: call_api
  states:
    call_api:
      type: task
      task:
        kind: httpCall:v1
        method: GET
        url: "https://api.example.com/missing/${context.inputId}"
        headers: { Accept: application/json }
        timeoutMs: 5000
        resultVar: api
      next: decide

    decide:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.api.ok == false
          next: failed
      default: done

    done:
      type: succeed
      outputVar: api

    failed:
      type: fail
      errorCode: DOWNSTREAM_ERROR
      reason: "Downstream returned non-2xx or network error"
