apiVersion: v1
kind: Journey
metadata:
  name: http-aggregate-errors
  version: 0.1.0
spec:
  input:
    schema:
      type: object
      required: [id]
      additionalProperties: true
      properties:
        id:
          type: string
  output:
    schema:
      type: object
      properties:
        status:
          type: integer
        ok:
          type: boolean
        headers:
          type: object
          additionalProperties:
            type: string
        body: {}
        error:
          type: object
          properties:
            type:
              type: string
            message:
              type: string
          additionalProperties: true
      additionalProperties: true
  # Error handling:
  # - Aggregates failures from multiple upstream HTTP calls.
  # - Exposes a simple custom error envelope `{status, ok, headers, body, error{type,message,...}}`
  #   as the journey’s external error structure, while the engine still uses Problem Details
  #   as the canonical internal error model (ADR-0003).
  apis:
    items: { openApiRef: apis/items.openapi.yaml }
    users: { openApiRef: apis/users.openapi.yaml }
    accounts: { openApiRef: apis/accounts.openapi.yaml }
    serviceA: { openApiRef: apis/serviceA.openapi.yaml }
    serviceB: { openApiRef: apis/serviceB.openapi.yaml }
  start: call_a
  states:
    call_a:
      type: task
      task:
        kind: httpCall
        method: GET
        url: "https://api.example.com/serviceA/${context.id}"
        headers: { Accept: application/json }
        timeoutMs: 5000
        resultVar: a
      next: call_b

    call_b:
      type: task
      task:
        kind: httpCall
        method: GET
        url: "https://api.example.com/serviceB/${context.id}"
        headers: { Accept: application/json }
        timeoutMs: 5000
        resultVar: b
      next: decide

    decide:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                (context.a.ok == false) or (context.b.ok == false)
          next: failed
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.a.ok == true and context.b.ok == true
          next: done
      default: failed

    done:
      type: succeed
      outputVar: b

    failed:
      type: fail
      errorCode: UPSTREAM_FAILURE
      reason: "One or more upstream calls failed"
