apiVersion: v1
kind: Journey
metadata:
  name: wait-approval
  version: 0.1.0
spec:
  input:
    schema:
      type: object
      required: [id, name]
      properties:
        id:
          type: string
        name:
          type: string
      additionalProperties: true
  output:
    schema:
      type: object
      properties:
        status:
          type: integer
        ok:
          type: boolean
        body:
          type: object
      additionalProperties: true
  # Provisional example: 'wait' state specified by DSL; engine support arrives in a later feature.
  start: submit
  states:
    submit:
      type: task
      task:
        kind: httpCall:v1
        operationRef: items.createItem
        params:
          headers: { Accept: application/json }
        body:
          mapper:
            lang: dataweave
            expr: |
              {
                id: context.id,
                name: context.name
              }
        timeoutMs: 5000
        resultVar: api
      next: waitForApproval

    waitForApproval:
      type: wait
      wait:
        channel: manual
        input:
          schema:
            description: Manual approval input
            type: object
            required: [decision]
            properties:
              decision:
                type: string
                enum: [approved, rejected]
              comment:
                type: string
            additionalProperties: false
        response:
          outputVar: stepResponse
          schema:
            title: wait-approval step response
            type: object
            description: Additional top-level fields returned from the waitForApproval step.
            properties:
              decision:
                type: string
                enum: [approved, rejected]
                description: The decision recorded at the approval step.
              comment:
                type: string
                description: Optional free-text comment provided by the approver.
            additionalProperties: true
        default: ingestWaitForApproval

    ingestWaitForApproval:
      type: transform
      transform:
        mapper:
          lang: dataweave
          expr: |
            context ++ {
              approval: context.payload,
              stepResponse: {
                decision: context.payload.decision,
                comment: context.payload.comment
              }
            }
        target:
          kind: context
      next: routeWaitForApproval

    routeWaitForApproval:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.payload.decision == 'approved'
          next: finish
      default: rejected

    finish:
      type: succeed
      outputVar: api

    rejected:
      type: fail
      errorCode: REJECTED
      reason: "Approval was rejected"
