apiVersion: v1
kind: Journey
metadata:
  name: subject-step-guard
  version: 0.1.0
spec:
  start: validateJwt

  states:
    validateJwt:
      type: task
      task:
        kind: jwtValidate:v1
        profile: default
      next: captureOwner

    captureOwner:
      type: transform
      transform:
        mapper:
          lang: dataweave
          expr: |
            context ++ {
              ownerUserId: context.auth.jwt.claims.sub
            }
        target:
          kind: context
          path: ""
      next: waitForUserAction

    waitForUserAction:
      type: wait
      wait:
        channel: manual
        input:
          schema:
            type: object
            properties:
              decision: { type: string }
            additionalProperties: true
        apply:
          mapper:
            lang: dataweave
            expr: |
              context ++ {
                stepUserId: context.auth.jwt.claims.sub,
                lastPayload: payload
              }
        on:
          - when:
              predicate:
                lang: dataweave
                expr: |
                  context.stepUserId == context.ownerUserId
            next: proceed
      default: subjectMismatch

    proceed:
      type: succeed
      outputVar: lastPayload

    subjectMismatch:
      type: fail
      errorCode: SUBJECT_MISMATCH
      reason: "Authenticated principal does not match journey owner"
