apiVersion: v1
kind: Journey
metadata:
  name: http-chained-calls
  version: 0.1.0
spec:
  apis:
    users: { openApiRef: apis/users.openapi.yaml }
    accounts: { openApiRef: apis/accounts.openapi.yaml }
  input:
    schema:
      title: http-chained-calls input context
      type: object
      required: [userId]
      properties:
        userId:
          type: string
      additionalProperties: true
  output:
    schema:
      title: http-chained-calls output
      type: object
      properties:
        status:
          type: integer
        ok:
          type: boolean
        headers:
          type: object
          additionalProperties:
            type: string
        body:
          type: object
          properties:
            accountId:
              type: string
            ownerId:
              type: string
            email:
              type: string
              format: email
          additionalProperties: true
        error:
          type: object
          properties:
            type:
              type: string
            message:
              type: string
          additionalProperties: true
      additionalProperties: true
  start: lookup
  states:
    lookup:
      type: task
      task:
        kind: httpCall:v1
        operationRef: users.getUserById
        params:
          path: { userId: "${context.userId}" }
          headers: { Accept: application/json }
        timeoutMs: 5000
        resultVar: a
      next: route

    route:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.a.ok == true and context.a.body.active == true
          next: create
      default: inactive

    create:
      type: task
      task:
        kind: httpCall:v1
        operationRef: accounts.createAccount
        params:
          headers: { Accept: application/json }
        body:
          mapper:
            lang: dataweave
            expr: |
              {
                ownerId: context.userId,
                email: context.a.body.email
              }
        timeoutMs: 5000
        resultVar: b
      next: decide_create

    decide_create:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.b.ok == true and context.b.status == 201
          next: done
      default: create_failed

    done:
      type: succeed
      outputVar: b

    inactive:
      type: fail
      errorCode: USER_INACTIVE
      reason: "User not active; create is not allowed"

    create_failed:
      type: fail
      errorCode: CREATE_FAILED
      reason: "Account creation failed or did not return 201"
