apiVersion: v1
kind: Journey
metadata:
  name: http-notify-audit
  version: 0.1.0
  description: Fire-and-forget HTTP audit notification for order updates.
spec:
  input:
    schema:
      title: http-notify-audit input context
      type: object
      required: [orderId]
      properties:
        orderId:
          type: string
      additionalProperties: true
  output:
    schema:
      title: http-notify-audit output
      type: object
      properties:
        orderId:
          type: string
      additionalProperties: true

  start: notify
  states:
    notify:
      type: task
      task:
        kind: httpCall:v1
        mode: notify
        method: POST
        url: "https://api.example.com/audit"
        headers:
          Accept: application/json
        body:
          mapper:
            lang: dataweave
            expr: |
              {
                event: "ORDER_UPDATED",
                orderId: context.orderId
              }
      next: done

    done:
      type: succeed
      # return the (unchanged) context; this journey does not depend on the HTTP outcome
