apiVersion: v1
kind: Journey
metadata:
  name: customer-onboarding-kyc
  version: 0.1.0
  description: Customer onboarding journey for individual KYC with external checks and account provisioning.
spec:
  apis:
    kycChecks: { openApiRef: apis/kyc-checks.openapi.yaml }
    amlScreening: { openApiRef: apis/aml-screening.openapi.yaml }
    customers: { openApiRef: apis/customers.openapi.yaml }
    accounts: { openApiRef: apis/accounts.openapi.yaml }
  input:
    schema:
      title: CustomerOnboardingKycStartRequest
      type: object
      required:
        - customerId
        - fullName
        - email
      properties:
        customerId:
          type: string
        fullName:
          type: string
        email:
          type: string
        dateOfBirth:
          type: string
          format: date
        nationality:
          type: string
        channel:
          type: string
      additionalProperties: true
  output:
    schema:
      title: CustomerOnboardingKycOutcome
      type: object
      required:
        - customerId
        - finalStatus
      properties:
        customerId:
          type: string
        finalStatus:
          type: string
          enum:
            - APPROVED
            - REJECTED
        kycResult:
          type: object
        amlResult:
          type: object
        riskDecision:
          type: object
        customerRecord:
          type: object
        account:
          type: object
        rejectionReason:
          type: string
      additionalProperties: true
  start: createProspect
  states:
    createProspect:
      type: task
      task:
        kind: httpCall:v1
        operationRef: customers.createCustomer
        params:
          headers:
            Accept: application/json
        body:
          mapper:
            lang: dataweave
            expr: |
              {
                customerId: context.customerId,
                fullName: context.fullName,
                email: context.email
              }
        timeoutMs: 3000
        resultVar: prospect
      next: waitForKycDocuments

    waitForKycDocuments:
      type: wait
      wait:
        channel: manual
        input:
          schema:
            description: Customer document upload and additional KYC details.
            type: object
            required:
              - decision
            properties:
              decision:
                type: string
                enum:
                  - submit
              documents:
                type: array
                items:
                  type: object
              notes:
                type: string
            additionalProperties: false
        response:
          outputVar: kycDocumentsResponse
          schema:
            title: KycDocumentsProjection
            type: object
            description: Additional top-level fields returned from the submitKycDocuments step.
            properties:
              decision:
                type: string
                enum:
                  - submit
              documents:
                type: array
                items:
                  type: object
              notes:
                type: string
            additionalProperties: true
        default: ingestWaitForKycDocuments

    ingestWaitForKycDocuments:
      type: transform
      transform:
        mapper:
          lang: dataweave
          expr: |
            context ++ {
              kycDocuments: context.payload,
              kycDocumentsResponse: {
                decision: context.payload.decision,
                documents: context.payload.documents,
                notes: context.payload.notes
              }
            }
        target:
          kind: context
      next: routeWaitForKycDocuments

    routeWaitForKycDocuments:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.payload.decision == "submit"
          next: triggerChecks
      default: rejected

    triggerChecks:
      type: parallel
      parallel:
        branches:
          - name: kyc
            start: startKyc
            states:
              startKyc:
                type: task
                task:
                  kind: httpCall:v1
                  operationRef: kycChecks.startKycCheck
                  params:
                    headers:
                      Accept: application/json
                  body:
                    mapper:
                      lang: dataweave
                      expr: |
                        {
                          customerId: context.customerId,
                          fullName: context.fullName,
                          dateOfBirth: context.dateOfBirth,
                          nationality: context.nationality
                        }
                  timeoutMs: 3000
                  resultVar: result
                next: done
              done:
                type: succeed
          - name: aml
            start: startAml
            states:
              startAml:
                type: task
                task:
                  kind: httpCall:v1
                  operationRef: amlScreening.startAmlScreening
                  params:
                    headers:
                      Accept: application/json
                  body:
                    mapper:
                      lang: dataweave
                      expr: |
                        {
                          customerId: context.customerId,
                          fullName: context.fullName
                        }
                  timeoutMs: 3000
                  resultVar: result
                next: done
              done:
                type: succeed
        join:
          strategy: allOf
          errorPolicy: collectAll
      next: waitForKycResult

    waitForKycResult:
      type: webhook
      webhook:
        input:
          schema:
            title: KYC result callback input
            type: object
            required:
              - customerId
              - status
            properties:
              customerId:
                type: string
              status:
                type: string
                enum:
                  - APPROVED
                  - REFERRED
                  - REJECTED
              reasons:
                type: array
                items:
                  type: string
            additionalProperties: true
        response:
          outputVar: kycResultResponse
          schema:
            title: KycResultProjection
            type: object
            description: Additional top-level fields returned from the submitKycResult webhook step.
            properties:
              status:
                type: string
              reasons:
                type: array
                items:
                  type: string
            additionalProperties: true
      next: validateKycResultSecret

    validateKycResultSecret:
      type: task
      task:
        kind: apiKeyValidate:v1
        profile: customer-onboarding-kyc-kyc
        source:
          location: header
          name: X-Kyc-Result-Secret
      next: routeKycResultAuth

    routeKycResultAuth:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.auth.apiKey.problem == null
          next: ingestWaitForKycResult
      default: waitForKycResult

    ingestWaitForKycResult:
      type: transform
      transform:
        mapper:
          lang: dataweave
          expr: |
            context ++ {
              kycResult: context.payload,
              kycResultResponse: {
                status: context.payload.status,
                reasons: context.payload.reasons
              }
            }
        target:
          kind: context
      next: routeWaitForKycResult

    routeWaitForKycResult:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.payload.status == "APPROVED"
                  or context.payload.status == "REFERRED"
          next: waitForAmlResult
      default: rejected

    waitForAmlResult:
      type: webhook
      webhook:
        input:
          schema:
            title: AML result callback input
            type: object
            required:
              - customerId
              - status
            properties:
              customerId:
                type: string
              status:
                type: string
                enum:
                  - CLEAR
                  - REFERRED
                  - REJECTED
              reasons:
                type: array
                items:
                  type: string
            additionalProperties: true
        response:
          outputVar: amlResultResponse
          schema:
            title: AmlResultProjection
            type: object
            description: Additional top-level fields returned from the submitAmlResult webhook step.
            properties:
              status:
                type: string
              reasons:
                type: array
                items:
                  type: string
            additionalProperties: true
      next: validateAmlResultSecret

    validateAmlResultSecret:
      type: task
      task:
        kind: apiKeyValidate:v1
        profile: customer-onboarding-kyc-aml
        source:
          location: header
          name: X-Aml-Result-Secret
      next: routeAmlResultAuth

    routeAmlResultAuth:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.auth.apiKey.problem == null
          next: ingestWaitForAmlResult
      default: waitForAmlResult

    ingestWaitForAmlResult:
      type: transform
      transform:
        mapper:
          lang: dataweave
          expr: |
            context ++ {
              amlResult: context.payload,
              amlResultResponse: {
                status: context.payload.status,
                reasons: context.payload.reasons
              }
            }
        target:
          kind: context
      next: routeWaitForAmlResult

    routeWaitForAmlResult:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.payload.status == "CLEAR"
                  or context.payload.status == "REFERRED"
          next: waitForRiskDecision
      default: rejected

    waitForRiskDecision:
      type: webhook
      webhook:
        input:
          schema:
            title: Risk decision callback input
            type: object
            required:
              - customerId
              - decision
            properties:
              customerId:
                type: string
              decision:
                type: string
                enum:
                  - APPROVE
                  - REJECT
              riskRating:
                type: string
              reason:
                type: string
            additionalProperties: true
        response:
          outputVar: riskDecisionResponse
          schema:
            title: RiskDecisionProjection
            type: object
            description: Additional top-level fields returned from the submitRiskDecision webhook step.
            properties:
              decision:
                type: string
              riskRating:
                type: string
              reason:
                type: string
            additionalProperties: true
      next: validateRiskDecisionSecret

    validateRiskDecisionSecret:
      type: task
      task:
        kind: apiKeyValidate:v1
        profile: customer-onboarding-kyc-risk
        source:
          location: header
          name: X-Risk-Decision-Secret
      next: routeRiskDecisionAuth

    routeRiskDecisionAuth:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.auth.apiKey.problem == null
          next: ingestWaitForRiskDecision
      default: waitForRiskDecision

    ingestWaitForRiskDecision:
      type: transform
      transform:
        mapper:
          lang: dataweave
          expr: |
            context ++ {
              riskDecision: context.payload,
              riskDecisionResponse: {
                decision: context.payload.decision,
                riskRating: context.payload.riskRating,
                reason: context.payload.reason
              }
            }
        target:
          kind: context
      next: routeWaitForRiskDecision

    routeWaitForRiskDecision:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.payload.decision == "APPROVE"
          next: createAccount
      default: rejected

    createAccount:
      type: task
      task:
        kind: httpCall:v1
        operationRef: accounts.createAccount
        params:
          headers:
            Accept: application/json
        body:
          mapper:
            lang: dataweave
            expr: |
              {
                ownerId: context.customerId,
                email: context.email
              }
        timeoutMs: 3000
        resultVar: accountCreation
      next: completeApproved

    completeApproved:
      type: succeed
      outputVar: riskDecision

    rejected:
      type: fail
      errorCode: ONBOARDING_REJECTED
      reason: "Customer onboarding rejected based on KYC/AML checks, missing documents, or risk decision"
