apiVersion: v1
kind: Journey
metadata:
  name: http-success
  version: 0.1.0
  description: Simple HTTP 200 success path with JSON body.
spec:
  apis:
    items: { openApiRef: apis/items.openapi.yaml }
    users: { openApiRef: apis/users.openapi.yaml }
    accounts: { openApiRef: apis/accounts.openapi.yaml }
    serviceA: { openApiRef: apis/serviceA.openapi.yaml }
    serviceB: { openApiRef: apis/serviceB.openapi.yaml }
  platform:
    config:
      itemsApiBaseUrl:
        type: string
        required: true
        description: "Base URL for the upstream items API"
  input:
    schema:
      title: JourneyStartRequest
      type: object
      required: [inputId]
      properties:
        inputId:
          type: string
      additionalProperties: true
  output:
    schema:
      title: HttpSuccessOutput
      type: object
      required: [ok]
      properties:
        status:
          type: integer
        ok:
          type: boolean
        headers:
          type: object
          additionalProperties:
            type: string
        body: {}
        error:
          type: object
          properties:
            type:
              type: string
            message:
              type: string
          required: [type]
          additionalProperties: true
      additionalProperties: true
  start: call_api
  states:
    call_api:
      type: task
      task:
        kind: httpCall
        method: GET
        url: "${platform.config.itemsApiBaseUrl}/items/${context.inputId}"
        headers: { Accept: application/json }
        timeoutMs: 5000
        resultVar: api
      next: decide

    decide:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.api.ok == true
          next: done
      default: failure

    done:
      type: succeed
      outputVar: api

    failure:
      type: fail
      errorCode: HTTP_NOT_OK
      reason: "HTTP call did not succeed"
