apiVersion: v1
kind: Journey
metadata:
  name: auth-jwt-mtls
  version: 0.1.0
spec:
  input:
    schema:
      type: object
      additionalProperties: true

  output:
    schema:
      type: object
      properties:
        subjectDn:
          type: string
        subject:
          type: string
      additionalProperties: true

  start: validateMtls

  states:
    validateMtls:
      type: task
      task:
        kind: mtlsValidate:v1
        profile: default
      next: validateJwt

    validateJwt:
      type: task
      task:
        kind: jwtValidate:v1
        profile: default
      next: checkCombinedPolicy

    checkCombinedPolicy:
      type: choice
      choices:
        - when:
            predicate:
              # Example combined authZ: require that JWT scopes include "admin"
              # and that the client certificate subject DN contains "OU=AdminClients".
              lang: dataweave
              expr: |
                (context.auth.jwt.claims.scope default "") contains "admin"
                  and (context.auth.mtls.subjectDn default "") contains "OU=AdminClients"
          next: done
      default: accessDenied

    done:
      type: succeed
      outputVar: auth

    accessDenied:
      type: fail
      errorCode: AUTHZ_DENIED
      reason: "Combined JWT + mTLS policy not satisfied"
