apiVersion: v1
kind: Journey
metadata:
  name: choice-multi-branch
  version: 0.1.0
spec:
  input:
    schema:
      type: object
      required: [inputId]
      additionalProperties: true
      properties:
        inputId:
          type: string
  output:
    schema:
      type: object
      properties:
        status:
          type: integer
        ok:
          type: boolean
        headers:
          type: object
          additionalProperties:
            type: string
        body: {}
        error:
          type: object
          properties:
            type:
              type: string
            message:
              type: string
          additionalProperties: true
      additionalProperties: true
  apis:
    items: { openApiRef: apis/items.openapi.yaml }
    users: { openApiRef: apis/users.openapi.yaml }
    accounts: { openApiRef: apis/accounts.openapi.yaml }
    serviceA: { openApiRef: apis/serviceA.openapi.yaml }
    serviceB: { openApiRef: apis/serviceB.openapi.yaml }
  start: call
  states:
    call:
      type: task
      task:
        kind: httpCall
        method: GET
        url: "https://api.example.com/items/${context.inputId}"
        headers: { Accept: application/json }
        timeoutMs: 5000
        resultVar: api
      next: route

    route:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.api.ok == true and context.api.body.status == 'APPROVED'
          next: approved
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.api.ok == true and context.api.body.status == 'REVIEW'
          next: review
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.api.ok == false
          next: tech_fail
      default: rejected

    approved:
      type: succeed
      outputVar: api

    review:
      type: succeed
      outputVar: api

    tech_fail:
      type: fail
      errorCode: DOWNSTREAM
      reason: "Technical failure"

    rejected:
      type: fail
      errorCode: BUSINESS_REJECTED
      reason: "Business rule rejected"
