apiVersion: v1
kind: Journey
metadata:
  name: event-publish-kafka
  version: 0.1.0
  description: Publish an order event to Kafka using DataWeave mappers.
spec:
  inputSchemaRef: schemas/event-publish-kafka-input.json
  outputSchemaRef: schemas/event-publish-kafka-output.json

  start: emitEvent
  states:
    emitEvent:
      type: task
      task:
        kind: eventPublish
        eventPublish:
          transport: kafka
          topic: orders.events
          key:
            mapper:
              lang: dataweave
              expr: |
                context.orderId
          value:
            mapper:
              lang: dataweave
              expr: |
                {
                  eventType: "ORDER_UPDATED",
                  orderId: context.orderId,
                  amount: context.amount,
                  status: context.status
                }
          headers:
            traceparent: "${context.traceparent}"
            source: "journeyforge"
          keySchemaRef: schemas/event-publish-kafka-key.json
          valueSchemaRef: schemas/event-publish-kafka-value.json
      next: done

    done:
      type: succeed
      # The journey does not rely on publish outcome; it can simply return context or a subset.
