apiVersion: v1
kind: Journey
metadata:
  name: http-notify-audit
  version: 0.1.0
  description: Fire-and-forget HTTP audit notification for order updates.
spec:
  inputSchemaRef: schemas/http-notify-audit-input.json
  outputSchemaRef: schemas/http-notify-audit-output.json

  start: notify
  states:
    notify:
      type: task
      task:
        kind: httpCall
        mode: notify
        method: POST
        url: "https://api.example.com/audit"
        headers:
          Accept: application/json
        body:
          mapper:
            lang: dataweave
            expr: |
              {
                event: "ORDER_UPDATED",
                orderId: context.orderId
              }
      next: done

    done:
      type: succeed
      # return the (unchanged) context; this journey does not depend on the HTTP outcome
