apiVersion: v1
kind: Journey
metadata:
  name: http-post-json
  version: 0.1.0
  description: HTTP POST with JSON request and response bodies.
spec:
  inputSchemaRef: schemas/http-post-json-input.json
  outputSchemaRef: schemas/http-post-json-output.json
  apis:
    items: { openApiRef: apis/items.openapi.yaml }
    users: { openApiRef: apis/users.openapi.yaml }
    accounts: { openApiRef: apis/accounts.openapi.yaml }
    serviceA: { openApiRef: apis/serviceA.openapi.yaml }
    serviceB: { openApiRef: apis/serviceB.openapi.yaml }
  start: create
  states:
    create:
      type: task
      task:
        kind: httpCall
        method: POST
        url: "https://api.example.com/items"
        headers:
          Content-Type: application/json
          Accept: application/json
        # Note: string body supports interpolation; objects are static
        body: |
          {"id": "${context.inputId}", "name": "example"}
        timeoutMs: 5000
        resultVar: api
      next: decide

    decide:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.api.ok == true and context.api.status == 201
          next: done
      default: failure

    done:
      type: succeed
      outputVar: api

    failure:
      type: fail
      errorCode: CREATE_FAILED
      reason: "POST did not return 201 or failed"
