apiVersion: v1
kind: Journey
metadata:
  name: http-resilience-degrade
  version: 0.1.0
spec:
  apis:
    serviceA: { openApiRef: apis/serviceA.openapi.yaml }
  input:
    schema:
      type: object
      additionalProperties: true
      properties:
        id:
          type: string
  output:
    schema:
      type: object
      properties:
        status:
          type: integer
        ok:
          type: boolean
        headers:
          type: object
          additionalProperties:
            type: string
        body: {}
        error:
          type: object
          properties:
            type:
              type: string
            message:
              type: string
          additionalProperties: true
      additionalProperties: true
  # Error handling:
  # - Uses an HTTP resilience policy with retries and then classifies the final outcome as success vs degraded failure.
  # - The `{status, ok, headers, body, error{type,message,...}}` shape is a custom error envelope for this journey;
  #   internally, the canonical error model remains Problem Details (ADR-0003), with `errorCode`/`reason` providing
  #   the stable external error code and summary.
  policies:
    httpResilience:
      default: standard
      definitions:
        standard:
          maxAttempts: 3
          retryOn: [NETWORK_ERROR, HTTP_5XX]
          backoff:
            initialDelayMs: 200
            maxDelayMs: 2000
            factor: 2.0
  start: call_upstream
  states:
    call_upstream:
      type: task
      task:
        kind: httpCall
        operationRef: serviceA.unstableOperation
        params:
          headers: { Accept: application/json }
        timeoutMs: 2000
        resultVar: api
        resiliencePolicyRef: standard
      next: decide

    decide:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.api.ok == true
          next: success
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.api.ok == false
          next: degraded
      default: degraded

    success:
      type: succeed
      outputVar: api

    degraded:
      type: fail
      errorCode: DEGRADED_UPSTREAM
      reason: "Upstream unstableOperation failed after retries"
