apiVersion: v1
kind: Workflow
metadata:
  name: http-success
  version: 0.1.0
spec:
  apis:
    items: { openApiRef: apis/items.openapi.yaml }
    users: { openApiRef: apis/users.openapi.yaml }
    accounts: { openApiRef: apis/accounts.openapi.yaml }
    serviceA: { openApiRef: apis/serviceA.openapi.yaml }
    serviceB: { openApiRef: apis/serviceB.openapi.yaml }
  inputSchemaRef: schemas/http-success-input.json
  outputSchemaRef: schemas/http-success-output.json
  start: call_api
  states:
    call_api:
      type: task
      task:
        kind: httpCall
        method: GET
        url: "https://api.example.com/items/${context.inputId}"
        headers: { Accept: application/json }
        timeoutMs: 5000
        resultVar: api
      next: decide

    decide:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.api.ok == true
          next: done
      default: failure

    done:
      type: succeed
      outputVar: api

    failure:
      type: fail
      errorCode: HTTP_NOT_OK
      reason: "HTTP call did not succeed"
