apiVersion: v1
kind: Journey
metadata:
  name: http-timeout-branch
  version: 0.1.0
spec:
  inputSchemaRef: schemas/http-timeout-branch-input.json
  outputSchemaRef: schemas/http-timeout-branch-output.json
  apis:
    items: { openApiRef: apis/items.openapi.yaml }
    users: { openApiRef: apis/users.openapi.yaml }
    accounts: { openApiRef: apis/accounts.openapi.yaml }
    serviceA: { openApiRef: apis/serviceA.openapi.yaml }
    serviceB: { openApiRef: apis/serviceB.openapi.yaml }
  start: slow_call
  states:
    slow_call:
      type: task
      task:
        kind: httpCall
        method: GET
        url: "https://api.example.com/slow/${context.id}"
        headers: { Accept: application/json }
        timeoutMs: 1   # intentionally tiny for illustration
        resultVar: api
      next: decide

    decide:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.api.ok == false and context.api.error.type == 'TIMEOUT'
          next: degraded
      default: proceed

    degraded:
      type: fail
      errorCode: TIMEOUT
      reason: "Downstream timeout"

    proceed:
      type: succeed
      outputVar: api
