apiVersion: v1
kind: Journey
metadata:
  name: http-timeout-branch
  version: 0.1.0
spec:
  input:
    schema:
      type: object
      required: [id]
      additionalProperties: true
      properties:
        id:
          type: string
  output:
    schema:
      type: object
      properties:
        status:
          type: integer
        ok:
          type: boolean
        headers:
          type: object
          additionalProperties:
            type: string
        body: {}
        error:
          type: object
          properties:
            type:
              type: string
            message:
              type: string
          additionalProperties: true
      additionalProperties: true
  # Error handling:
  # - Inspects the structured HTTP result to detect timeouts explicitly and fails with a dedicated timeout error code.
  # - The `{status, ok, headers, body, error{type,message,...}}` shape is a custom error envelope; Problem Details
  #   remains the canonical internal model for errors (ADR-0003), with `errorCode`/`reason` surfacing a stable timeout code.
  apis:
    items: { openApiRef: apis/items.openapi.yaml }
    users: { openApiRef: apis/users.openapi.yaml }
    accounts: { openApiRef: apis/accounts.openapi.yaml }
    serviceA: { openApiRef: apis/serviceA.openapi.yaml }
    serviceB: { openApiRef: apis/serviceB.openapi.yaml }
  start: slow_call
  states:
    slow_call:
      type: task
      task:
        kind: httpCall
        method: GET
        url: "https://api.example.com/slow/${context.id}"
        headers: { Accept: application/json }
        timeoutMs: 1 # intentionally tiny for illustration
        resultVar: api
      next: decide

    decide:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.api.ok == false and context.api.error.type == 'TIMEOUT'
          next: degraded
      default: proceed

    degraded:
      type: fail
      errorCode: TIMEOUT
      reason: "Downstream timeout"

    proceed:
      type: succeed
      outputVar: api
