apiVersion: v1
kind: Api
metadata:
  name: http-chained-calls-api
  version: 0.1.0
spec:
  route:
    path: /apis/http-chained-calls
    method: POST

  apis:
    users:
      openApiRef: apis/users.openapi.yaml
    accounts:
      openApiRef: apis/accounts.openapi.yaml

  inputSchemaRef: schemas/http-chained-calls-input.json
  outputSchemaRef: schemas/http-chained-calls-output.json

  defaults:
    http:
      timeoutMs: 5000
      headers:
        Accept: application/json

  start: lookup
  states:
    lookup:
      type: task
      task:
        kind: httpCall
        operationRef: users.getUserById
        params:
          path:
            userId: "${context.userId}"
        resultVar: user
      next: route

    route:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.user.ok == true and context.user.body.active == true
          next: create
      default: inactive

    create:
      type: task
      task:
        kind: httpCall
        operationRef: accounts.createAccount
        body:
          mapper:
            lang: dataweave
            expr: |
              {
                ownerId: context.userId,
                email: context.user.body.email
              }
        resultVar: account
      next: decideCreate

    decideCreate:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.account.ok == true and context.account.status == 201
          next: done
      default: create_failed

    done:
      type: succeed
      outputVar: account

    inactive:
      type: fail
      errorCode: USER_INACTIVE
      reason: "User not active; account creation is not allowed"

    create_failed:
      type: fail
      errorCode: CREATE_FAILED
      reason: "Account creation failed or did not return 201"
