apiVersion: v1
kind: Journey
metadata:
  name: http-failure-branch
  version: 0.1.0
spec:
  inputSchemaRef: schemas/http-failure-branch-input.json
  outputSchemaRef: schemas/http-failure-branch-output.json
  apis:
    items: { openApiRef: apis/items.openapi.yaml }
    users: { openApiRef: apis/users.openapi.yaml }
    accounts: { openApiRef: apis/accounts.openapi.yaml }
    serviceA: { openApiRef: apis/serviceA.openapi.yaml }
    serviceB: { openApiRef: apis/serviceB.openapi.yaml }
  start: call_api
  states:
    call_api:
      type: task
      task:
        kind: httpCall
        method: GET
        url: "https://api.example.com/missing/${context.inputId}"
        headers: { Accept: application/json }
        timeoutMs: 5000
        resultVar: api
      next: decide

    decide:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.api.ok == false
          next: failed
      default: done

    done:
      type: succeed
      outputVar: api

    failed:
      type: fail
      errorCode: DOWNSTREAM_ERROR
      reason: "Downstream returned non-2xx or network error"
