apiVersion: v1
kind: Journey
metadata:
  name: http-content-check
  version: 0.1.0
spec:
  inputSchemaRef: schemas/http-content-check-input.json
  outputSchemaRef: schemas/http-content-check-output.json
  apis:
    items: { openApiRef: apis/items.openapi.yaml }
    users: { openApiRef: apis/users.openapi.yaml }
    accounts: { openApiRef: apis/accounts.openapi.yaml }
    serviceA: { openApiRef: apis/serviceA.openapi.yaml }
    serviceB: { openApiRef: apis/serviceB.openapi.yaml }
  start: call_api
  states:
    call_api:
      type: task
      task:
        kind: httpCall
        method: GET
        url: "https://api.example.com/items/${context.inputId}"
        headers: { Accept: application/json }
        timeoutMs: 5000
        resultVar: api
      next: decide

    decide:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.api.ok == true and (context.api.body.status == 'OK' or context.api.status == 200)
          next: approved
      default: rejected

    approved:
      type: succeed
      outputVar: api

    rejected:
      type: fail
      errorCode: CONTENT_REJECTED
      reason: "Business rule not satisfied"
