apiVersion: v1
kind: Workflow
metadata:
  name: multitenant-routing
  version: 0.1.0
spec:
  apis:
    itemsA: { openApiRef: apis/items.openapi.yaml }
    itemsB: { openApiRef: apis/serviceA.openapi.yaml }
  inputSchemaRef: schemas/multitenant-routing-input.json
  outputSchemaRef: schemas/multitenant-routing-output.json
  httpBindings:
    start:
      headersToContext:
        X-Tenant-Id: tenantId
  start: routeTenant
  states:
    routeTenant:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.tenantId == 'A'
          next: callTenantA
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.tenantId == 'B'
          next: callTenantB
      default: unsupported

    callTenantA:
      type: task
      task:
        kind: httpCall
        operationRef: itemsA.getItemById
        params:
          path: { id: "${context.id}" }
          headers: { Accept: application/json, X-Tenant-Id: "${context.tenantId}" }
        timeoutMs: 5000
        resultVar: api
      next: decide

    callTenantB:
      type: task
      task:
        kind: httpCall
        operationRef: itemsB.getItem
        params:
          headers: { Accept: application/json, X-Tenant-Id: "${context.tenantId}" }
        timeoutMs: 5000
        resultVar: api
      next: decide

    decide:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.api.ok == true
          next: done
      default: failed

    done:
      type: succeed
      outputVar: api

    failed:
      type: fail
      errorCode: TENANT_CALL_FAILED
      reason: "Tenant-specific call failed"

    unsupported:
      type: fail
      errorCode: TENANT_UNSUPPORTED
      reason: "Unsupported tenant id"
