apiVersion: v1
kind: Workflow
metadata:
  name: payment-callback
  version: 0.1.0
spec:
  apis:
    payments: { openApiRef: apis/payments.openapi.yaml }
  inputSchemaRef: schemas/payment-callback-input.json
  outputSchemaRef: schemas/payment-callback-output.json
  start: authorize
  states:
    authorize:
      type: task
      task:
        kind: httpCall
        operationRef: payments.authorizePayment
        params:
          path: { paymentId: "${context.paymentId}" }
          headers: { Accept: application/json }
        body:
          mapper:
            lang: dataweave
            expr: |
              {
                amount: context.amount,
                currency: context.currency
              }
        timeoutMs: 5000
        resultVar: auth
      next: waitForCallback

    waitForCallback:
      type: webhook
      webhook:
        inputSchemaRef: schemas/payment-callback-webhook-input.json
        security:
          kind: sharedSecretHeader
          header: X-Webhook-Secret
          secretRef: secret://webhook/payments-callback
        apply:
          mapper:
            lang: dataweave
            expr: |
              context ++ { 'webhook': payload }
        on:
          - when:
              predicate:
                lang: dataweave
                expr: |
                  payload.status == 'SUCCESS'
            next: captured
        default: failed

    captured:
      type: succeed
      outputVar: webhook

    failed:
      type: fail
      errorCode: PAYMENT_FAILED
      reason: "Payment callback indicated failure or did not arrive as expected"
