apiVersion: v1
kind: Journey
metadata:
  name: payment-callback
  version: 0.1.0
  description: Handle payment authorization and callback completion.
spec:
  apis:
    payments: { openApiRef: apis/payments.openapi.yaml }
  input:
    schema:
      title: payment-callback input context
      type: object
      required: [paymentId, amount, currency]
      properties:
        paymentId:
          type: string
        amount:
          type: number
        currency:
          type: string
      additionalProperties: true
  output:
    schema:
      title: payment-callback output
      type: object
      properties:
        status:
          type: string
          enum: [SUCCESS, FAILED]
        paymentId:
          type: string
        amount:
          type: number
        currency:
          type: string
        reason:
          type: string
      additionalProperties: true
  start: authorize
  states:
    authorize:
      type: task
      task:
        kind: httpCall
        operationRef: payments.authorizePayment
        params:
          path: { paymentId: "${context.paymentId}" }
          headers: { Accept: application/json }
        body:
          mapper:
            lang: dataweave
            expr: |
              {
                amount: context.amount,
                currency: context.currency
              }
        timeoutMs: 5000
        resultVar: auth
      next: waitForCallback

    waitForCallback:
      type: webhook
      webhook:
        input:
          schema:
            title: payment-callback webhook input
            type: object
            required: [paymentId, status]
            properties:
              paymentId:
                type: string
              status:
                type: string
                enum: [SUCCESS, FAILED]
              reason:
                type: string
            additionalProperties: true
        response:
          outputVar: callbackResponse
          schema:
            title: payment-callback step response
            type: object
            description: Additional top-level fields returned from the waitForCallback webhook step.
            properties:
              paymentId:
                type: string
                description: The payment id associated with this callback.
              status:
                type: string
                enum: [SUCCESS, FAILED]
                description: Callback status as reported by the payment provider.
              reason:
                type: string
                description: Optional failure reason when status is FAILED.
            additionalProperties: true
        security:
          kind: sharedSecretHeader
          header: X-Webhook-Secret
          secretRef: secret://webhook/payments-callback
        apply:
          mapper:
            lang: dataweave
            expr: |
              context ++ {
                webhook: payload,
                callbackResponse: {
                  paymentId: payload.paymentId,
                  status: payload.status,
                  reason: payload.reason
                }
              }
        on:
          - when:
              predicate:
                lang: dataweave
                expr: |
                  payload.status == 'SUCCESS'
            next: captured
        default: failed

    captured:
      type: succeed
      outputVar: webhook

    failed:
      type: fail
      errorCode: PAYMENT_FAILED
      reason: "Payment callback indicated failure or did not arrive as expected"
