apiVersion: v1
kind: Journey
metadata:
  name: sync-wrapper-wait
  version: 0.1.0
spec:
  input:
    schema:
      type: object
      properties:
        status:
          type: string
      additionalProperties: true
  output:
    schema:
      type: object
      properties:
        status:
          type: string
      additionalProperties: true
  start: startLongRunning
  states:
    startLongRunning:
      type: transform
      transform:
        mapper:
          lang: dataweave
          expr: |
            context ++ { 'startedAt': now() }
        target:
          kind: context
          path: ""
      next: waitStep

    waitStep:
      type: wait
      wait:
        channel: manual
        input:
          schema:
            type: object
            properties:
              status:
                type: string
            additionalProperties: true
        timeoutSec: 10
        onTimeout: timedOut
        apply:
          mapper:
            lang: dataweave
            expr: |
              context ++ { 'event': payload }
        on:
          - when:
              predicate:
                lang: dataweave
                expr: |
                  payload.status == 'DONE'
            next: done

    done:
      type: succeed
      outputVar: event

    timedOut:
      type: fail
      errorCode: OPERATION_TIMED_OUT
      reason: "No completion event received before timeout"
