apiVersion: v1
kind: Workflow
metadata:
  name: wait-approval
  version: 0.1.0
spec:
  inputSchemaRef: schemas/wait-approval-input.json
  outputSchemaRef: schemas/wait-approval-output.json
  # Provisional example: 'wait' state specified by DSL; runtime support arrives in a later feature.
  start: submit
  states:
    submit:
      type: task
      task:
        kind: httpCall
        operationRef: items.createItem
        params:
          headers: { Accept: application/json }
        body:
          mapper:
            lang: dataweave
            expr: |
              {
                id: context.id,
                name: context.name
              }
        timeoutMs: 5000
        resultVar: api
      next: waitForApproval

    waitForApproval:
      type: wait
      wait:
        channel: manual
        inputSchemaRef: schemas/wait-approval-approve-input.json
        apply:
          mapper:
            lang: dataweave
            expr: |
              context ++ { approval: payload }
        on:
          - when:
              predicate:
                lang: dataweave
                expr: |
                  payload.decision == 'approved'
            next: finish
        default: rejected

    finish:
      type: succeed
      outputVar: api

    rejected:
      type: fail
      errorCode: REJECTED
      reason: "Approval was rejected"
