apiVersion: v1
kind: Journey
metadata:
  name: http-content-check
  version: 0.1.0
spec:
  input:
    schema:
      type: object
      required: [inputId]
      additionalProperties: true
      properties:
        inputId:
          type: string
  output:
    schema:
      type: object
      properties:
        status:
          type: integer
        ok:
          type: boolean
        headers:
          type: object
          additionalProperties:
            type: string
        body: {}
        error:
          type: object
          properties:
            type:
              type: string
            message:
              type: string
          additionalProperties: true
      additionalProperties: true
  apis:
    items: { openApiRef: apis/items.openapi.yaml }
    users: { openApiRef: apis/users.openapi.yaml }
    accounts: { openApiRef: apis/accounts.openapi.yaml }
    serviceA: { openApiRef: apis/serviceA.openapi.yaml }
    serviceB: { openApiRef: apis/serviceB.openapi.yaml }
  start: call_api
  states:
    call_api:
      type: task
      task:
        kind: httpCall:v1
        method: GET
        url: "https://api.example.com/items/${context.inputId}"
        headers: { Accept: application/json }
        timeoutMs: 5000
        resultVar: api
      next: decide

    decide:
      type: choice
      choices:
        - when:
            predicate:
              lang: dataweave
              expr: |
                context.api.ok == true and (context.api.body.status == 'OK' or context.api.status == 200)
          next: approved
      default: rejected

    approved:
      type: succeed
      outputVar: api

    rejected:
      type: fail
      errorCode: CONTENT_REJECTED
      reason: "Business rule not satisfied"
